spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mohae-database.cizjan5etqcf.ap-northeast-2.rds.amazonaws.com:13306/mohae_db?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: admin
    password: ahgozbd2023!
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update    # 운영환경에서는 validate 로 변경
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  redis:
    host: localhost
    port: 6379
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
        transaction: DEBUG
server:
  servlet:
    encoding:
      force-response: true
mail:
  address:
    admin: mohae202303@gmail.com
jwt:
  key: Y29kZXN0YXRlc3NlYjQybWFpbjAwNm1vaGFlMjAyMw
  access-token-expiration-minutes: 1
  refresh-token-expiration-minutes: 2
cloud:
  aws:
    credentials:
      accessKey: AKIAU7XBFI4YLFJNDAOQ
      secretKey: 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
    s3:
      bucket: mohae-files
    region:
      static: ap-northeast-2
    stack:
      auto: false