spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  config:
    import: 'aws-parameterstore:'
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
        transaction: DEBUG
server:
  servlet:
    encoding:
      force-response: true
mail:
  address:
    admin: ${ADMIN_MAIL_ADDRESS}
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: ${ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration-minutes: ${REFRESH_TOKEN_EXPIRATION}
cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    s3:
      bucket: ${BUCKET_NAME}
    region:
      static: ap-northeast-2
    stack:
      auto: false
aws:
  paramstore:
    enabled: true
    prefix: /spring-boot-aws
    name: mohae
    profileSeparator: _
